# Generated by Django 4.1.13 on 2024-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('NON_FICTION', 'Non-fiction'), ('SCIENCE', 'Science'), ('HISTORY', 'History')], max_length=100, verbose_name='Genre'),
        ),
    ]
