# Generated by Django 4.1.13 on 2024-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_add_sample_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['published_date'], name='main_book_publish_61246a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='main_book_price_a6899a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['published_date', 'price'], name='main_book_publish_8aeefe_idx'),
        ),
    ]
